homeassistant:
  packages: !include_dir_named packages
  external_url: "https://homeassistant.uxnify.com"
  internal_url: "http://10.0.1.30:8123"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1
    - 172.30.0.0/16
    - 172.31.0.0/16
    - 192.168.1.0/24
    - 10.0.1.0/24
    - 10.0.2.0/24
    - fe80::/10
    - 100.64.0.0/10
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/kiosk-mode/kiosk-mode.js

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include sensors.yaml

lovelace:
  mode: "storage"
  resources:
    - type: "module"
      url: "/hacsfiles/button-card/button-card.js"
    - type: "module"
      url: "/hacsfiles/kiosk-mode/kiosk-mode.js"
    - type: "module"
      url: "/local/layout-card-modified/layout-card-modified.js"
    - type: "module"
      url: "/local/navbar-popup-caret/navbar-popup-caret.js"
    - type: "module"
      url: "/local/navbar-sidebar-offset/navbar-sidebar-offset.js"
    - type: "css"
      url: "/local/hemma/fonts/hanken-grotesk.css"
    - url: "/local/custom-lovelace/swipe-card/swipe-card.js"
      type: "module"
      
  dashboards:
    dashboard-hemma:
      mode: yaml
      title: "Hemma"
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards/hemma/hemma.yaml